-- HowieZZ Catalog Schema
-- Auto-generated by scripts/build_db.py — do not edit by hand

CREATE TABLE IF NOT EXISTS series (
    id          TEXT PRIMARY KEY,   -- 'I', 'K', 'Fusion'
    name        TEXT NOT NULL,
    folder      TEXT                -- relative path under assets/
);

CREATE TABLE IF NOT EXISTS bodies (
    code        TEXT PRIMARY KEY,   -- 'ZG170D', 'ZF168B', 'ZK168B'
    series_id   TEXT NOT NULL,
    body_line   TEXT,               -- 'ZK','ZG','ZGX','ZX','ZF' (code prefix)
    line_label  TEXT,               -- 'K-Series','I-Series','SLE 3.0','Fusion'
    height_cm   INTEGER,            -- nominal head+body height (from code)
    cup_size    TEXT,               -- cup letter (from code / spec card)
    spec_image  TEXT,               -- relative asset path to spec webp
    has_specs   INTEGER DEFAULT 0,  -- 1 if full measurements present
    FOREIGN KEY (series_id) REFERENCES series(id)
);

-- Full transcribed spec-card measurements (one row per body that has a card)
CREATE TABLE IF NOT EXISTS body_measurements (
    body_code         TEXT PRIMARY KEY,
    cup               TEXT,
    upper_bust        REAL,
    under_bust        REAL,
    waist             REAL,
    hip               REAL,
    neck              REAL,
    shoulder_width    REAL,
    arm_length        REAL,
    hand_length       REAL,
    leg_length        REAL,
    foot_length       REAL,
    thigh_circ        REAL,
    calf_circ         REAL,
    body_height       REAL,         -- naked body standing height
    head_body_height  REAL,         -- head+body height (null if card omits)
    weight_kg         REAL,
    spec_label        TEXT,         -- e.g. 'SLE 3.0'
    FOREIGN KEY (body_code) REFERENCES bodies(code)
);

CREATE TABLE IF NOT EXISTS heads (
    code        TEXT PRIMARY KEY,   -- 'GE149_1', 'KE03_1', 'ZFE01_1'
    series_id   TEXT NOT NULL,
    head_type   TEXT,               -- 'Hard' | 'Soft'
    FOREIGN KEY (series_id) REFERENCES series(id)
);

CREATE TABLE IF NOT EXISTS head_images (
    id          INTEGER PRIMARY KEY AUTOINCREMENT,
    head_code   TEXT NOT NULL,
    face_code   TEXT,               -- makeup code from filename parens, e.g. GE70MJ
    skin_tone   TEXT,               -- 'Fair' | 'Tan'
    variant     INTEGER DEFAULT 1,
    filename    TEXT NOT NULL,
    rel_path    TEXT NOT NULL,      -- relative to assets/
    FOREIGN KEY (head_code) REFERENCES heads(code)
);

CREATE TABLE IF NOT EXISTS products (
    code        TEXT PRIMARY KEY,   -- folder name (exact)
    head_code   TEXT,               -- e.g. GE149_1, KE03_1, ZFE01_1
    face_code   TEXT,               -- makeup/face code, e.g. GE74MJ (I-series)
    body_code   TEXT,               -- canonical body code (alias-resolved)
    raw_body    TEXT,               -- body code as it appeared in folder name
    photoshoot  INTEGER,            -- the -1 / -2 suffix (same head+body, diff shoot)
    series_id   TEXT NOT NULL,
    folder_path TEXT NOT NULL,      -- relative to assets/
    image_count INTEGER DEFAULT 0,
    video_count INTEGER DEFAULT 0,
    live_handle TEXT,               -- matched zelexdoll.com product handle
    live_title  TEXT,               -- live store product title
    price       TEXT,               -- representative variant price (USD)
    body_source TEXT,               -- 'folder' | 'live' (where body_code came from)
    FOREIGN KEY (series_id) REFERENCES series(id),
    FOREIGN KEY (head_code) REFERENCES heads(code),
    FOREIGN KEY (body_code) REFERENCES bodies(code)
);

-- Live store variants (one row per SKU) — pricing + configurable options
CREATE TABLE IF NOT EXISTS product_variants (
    sku              TEXT PRIMARY KEY,
    product_code     TEXT,          -- our folder, if matched
    live_handle      TEXT,
    head_code        TEXT,
    face_code        TEXT,
    body_code        TEXT,
    skin_tone        TEXT,
    price            TEXT,
    compare_at_price TEXT,
    option1          TEXT,
    option2          TEXT,
    option3          TEXT,
    title            TEXT
);

CREATE TABLE IF NOT EXISTS product_assets (
    id           INTEGER PRIMARY KEY AUTOINCREMENT,
    product_code TEXT NOT NULL,
    filename     TEXT NOT NULL,
    sequence     INTEGER,
    media_type   TEXT NOT NULL DEFAULT 'image',   -- 'image' | 'video'
    rel_path     TEXT NOT NULL,
    FOREIGN KEY (product_code) REFERENCES products(code)
);

CREATE TABLE IF NOT EXISTS options (
    id           INTEGER PRIMARY KEY AUTOINCREMENT,
    group_type   TEXT NOT NULL,     -- 'Body Options' | 'Head Options'
    category     TEXT NOT NULL,     -- 'Hand Type', 'Areola Color', etc.
    option_key   TEXT,              -- '1#', '2#', etc.
    label        TEXT,              -- 'Red', 'Hard Hand', etc. (may be null)
    filename     TEXT NOT NULL,
    rel_path     TEXT NOT NULL
);

CREATE TABLE IF NOT EXISTS body_specs (
    body_code   TEXT PRIMARY KEY,
    filename    TEXT NOT NULL,
    rel_path    TEXT NOT NULL
);

CREATE TABLE IF NOT EXISTS videos (
    id           INTEGER PRIMARY KEY AUTOINCREMENT,
    series_id    TEXT,
    filename     TEXT NOT NULL,
    label        TEXT,
    rel_path     TEXT NOT NULL,
    product_code TEXT
);
