#!/usr/bin/env python3
"""
Build db/neck_compatibility.json — the single source of truth for which heads
physically fit which bodies (the basis for interchangeable heads, PDR-011 §8).

Heads attach at the neck, so interchangeability is governed by the neck connector,
NOT the marketing line. The only measured proxy on the spec cards is neck
CIRCUMFERENCE, which clusters cleanly: K-Series ~27cm (narrow) vs Fusion /
I-Series / SLE ~31-33cm (standard). This script promotes that into an explicit,
reviewable per-body neck_class — instead of a magic constant living in page JS —
and leaves a `neck_joint_mm` slot (null) for the TRUE connector measurement.
Until that real spec is supplied, neck_class is circumference-derived (an
estimate); once `neck_joint_mm` is filled per body, classes should key off it.

This module also exports the threshold + helpers that scripts/build_heads.py
imports, so both files share one definition.

Sources: db/body_measurements.json (neck circumference per body)
Run before build_heads.py. Usage: python scripts/build_neck_compat.py
"""
import json
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
DB = ROOT / "db"
OUT = DB / "neck_compatibility.json"

# Threshold (cm) below which a neck is the narrow (K-Series) connector. ESTIMATE
# from spec-card circumferences — replace with a measured neck_joint_mm rule when
# the physical connector spec is available.
NECK_SLIM_MAX = 29.0

# line -> default neck class, used when a record has no measured neck
LINE_NECK_CLASS = {"K-Series": "slim", "I-Series": "standard", "Fusion": "standard", "SLE 3.0": "standard"}

# which body classes a head class fits (currently 1:1; widen here if a connector
# turns out to be cross-compatible once real joint specs land)
COMPATIBILITY = {"slim": ["slim"], "standard": ["standard"]}


def neck_class(neck_cm):
    """Circumference-derived neck class. Returns None when neck_cm is unknown."""
    if neck_cm is None:
        return None
    return "slim" if neck_cm < NECK_SLIM_MAX else "standard"


def main():
    bodies_meas = json.loads((DB / "body_measurements.json").read_text(encoding="utf-8")).get("bodies", {})

    bodies = {}
    for code in sorted(bodies_meas):
        b = bodies_meas[code]
        neck = b.get("neck")
        line = b.get("line")
        # normalize the SLE label used in measurements ("SLE 3.0") to the line name
        cls = neck_class(neck) or LINE_NECK_CLASS.get(line)
        bodies[code] = {
            "line": line,
            "neck_circ_cm": neck,
            "neck_class": cls,
            "neck_joint_mm": None,  # TRUE connector spec — pending physical confirmation
            "class_basis": "measured-circumference" if neck is not None else "line-default",
        }

    payload = {
        "version": "1.0.0",
        "_comment": (
            "Neck-connector compatibility — the basis for interchangeable heads (PDR-011 §8). "
            "neck_class is the compatibility key; heads fit a body when their classes match "
            "(see `compatibility`). neck_class is derived from spec-card neck CIRCUMFERENCE "
            f"(threshold {NECK_SLIM_MAX}cm) until a measured `neck_joint_mm` connector spec is "
            "supplied per body — fill neck_joint_mm to replace the estimate. Generated by "
            "scripts/build_neck_compat.py; consumed by build_heads.py and configurator.html."
        ),
        "generated_from": ["db/body_measurements.json"],
        "neck_slim_max_cm": NECK_SLIM_MAX,
        "classes": {
            "slim": {"neck_circ_cm_max": NECK_SLIM_MAX, "typical_lines": ["K-Series"], "connector": "narrow"},
            "standard": {"neck_circ_cm_min": NECK_SLIM_MAX, "typical_lines": ["Fusion", "I-Series", "SLE 3.0"], "connector": "standard"},
        },
        "compatibility": COMPATIBILITY,
        "count": len(bodies),
        "bodies": bodies,
    }
    OUT.write_text(json.dumps(payload, indent=2, ensure_ascii=False) + "\n", encoding="utf-8")

    by_class = {}
    for r in bodies.values():
        by_class[r["neck_class"]] = by_class.get(r["neck_class"], 0) + 1
    print(f"Wrote {OUT.relative_to(ROOT)} — {len(bodies)} bodies")
    for cls, n in sorted(by_class.items(), key=lambda kv: str(kv[0])):
        print(f"  {str(cls):10} {n}")
    missing = sum(1 for r in bodies.values() if r["neck_joint_mm"] is None)
    print(f"  awaiting measured neck_joint_mm: {missing} (class currently circumference-derived)")


if __name__ == "__main__":
    main()
