[CmdletBinding()]
param(
  [string]$Direction = "from-ccs",
  [string]$WorkspaceRoot = ".",
  [string]$CcsRoot = "C:/.05_Chromatic_Design_Studios"
)

Set-StrictMode -Version Latest
$ErrorActionPreference = "Stop"

function Normalize-Root([string]$PathValue) {
  if ([string]::IsNullOrWhiteSpace($PathValue) -or $PathValue -eq ".") {
    return (Get-Location).Path
  }
  return (Resolve-Path -Path $PathValue).Path
}

function Ensure-Directory([string]$PathValue) {
  if (-not (Test-Path -Path $PathValue)) {
    New-Item -ItemType Directory -Path $PathValue -Force | Out-Null
  }
}

$workspace = Normalize-Root $WorkspaceRoot
$ccs = Normalize-Root $CcsRoot

$sourceCcsDir = Join-Path $ccs "04_css_library"
$sourceWorkspaceFile = Join-Path $workspace "assets/ccs/chromatic-luxe-pilot.css"

$ccsTokenFile = Join-Path $sourceCcsDir "chromatic-luxe-tokens.css"
$ccsMotionFile = Join-Path $sourceCcsDir "chromatic-luxe-motion.css"

function Build-PilotFromCcs {
  if (-not (Test-Path -Path $ccsTokenFile)) { throw "Missing file: $ccsTokenFile" }
  if (-not (Test-Path -Path $ccsMotionFile)) { throw "Missing file: $ccsMotionFile" }

  Ensure-Directory (Split-Path -Parent $sourceWorkspaceFile)

  $tokenText = Get-Content -Raw -Path $ccsTokenFile
  $motionText = Get-Content -Raw -Path $ccsMotionFile

  $header = @(
    "/* Synced from C:/.05_Chromatic_Design_Studios/04_css_library */",
    "/* Source files:",
    "   - chromatic-luxe-tokens.css",
    "   - chromatic-luxe-motion.css",
    "   Generated by scripts/sync_chromatic_luxe.ps1 */",
    ""
  ) -join "`r`n"

  Set-Content -Path $sourceWorkspaceFile -Value ($header + $tokenText + "`r`n`r`n" + $motionText) -NoNewline
  Write-Output "Synced CCS -> workspace pilot: $sourceWorkspaceFile"
}

function Split-PilotToCcs {
  if (-not (Test-Path -Path $sourceWorkspaceFile)) { throw "Missing file: $sourceWorkspaceFile" }
  Ensure-Directory $sourceCcsDir

  $pilotText = Get-Content -Raw -Path $sourceWorkspaceFile
  $tokenMatch = [regex]::Match($pilotText, "(?s):root\s*\{.*?\}\s*")
  if (-not $tokenMatch.Success) {
    throw "Could not find token :root block in pilot file."
  }

  $motionStart = $tokenMatch.Index + $tokenMatch.Length
  $motionText = $pilotText.Substring($motionStart).Trim()

  $tokenHeader = "/* Synced from workspace pilot via scripts/sync_chromatic_luxe.ps1 */`r`n`r`n"
  $motionHeader = "/* Synced from workspace pilot via scripts/sync_chromatic_luxe.ps1 */`r`n`r`n"

  Set-Content -Path $ccsTokenFile -Value ($tokenHeader + $tokenMatch.Value.Trim() + "`r`n") -NoNewline
  Set-Content -Path $ccsMotionFile -Value ($motionHeader + $motionText + "`r`n") -NoNewline

  Write-Output "Synced workspace pilot -> CCS library: $sourceCcsDir"
}

switch ($Direction.ToLowerInvariant()) {
  "from-ccs" { Build-PilotFromCcs; break }
  "to-ccs" { Split-PilotToCcs; break }
  "both" {
    Build-PilotFromCcs
    Split-PilotToCcs
    break
  }
  default {
    throw "Invalid -Direction '$Direction'. Use from-ccs, to-ccs, or both."
  }
}
